Prepara avaliador para v3
betrybe/stryker-evaluator-action pull request #4
Opened 2021-01-15 10:59 UTC by jeanpsv

2021-01-15 11:01 UTC, jeanpsv commented on README.md
> -THIS README IS DEPRECATED AND HAS TO BE UPDATED.
@albertosca oq deve ser atualizado nesse readme?

2021-01-18 16:55 UTC, hurrycaner approved these changes

2021-01-19 16:48 UTC, eucleciojosias approved these changes

2021-01-19 17:41 UTC, LeandroLM approved these changes

2021-01-19 17:47 UTC, inaC requested changes

2021-01-19 17:47 UTC, inaC commented on README.md
>  ## Inputs
Você poderia remover essa seção `Inputs`, haja visto que ela possui mais nada, não?
```suggestion
```

2021-01-19 17:47 UTC, inaC commented on entrypoint.sh
>  npm install
O código será disponibilizado no runner num passo anterior, via uso da action `checkout`, certo? Nesse caso, você não precisaria acessar o diretório contendo código, via [variável de ambiente](https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables)  `GITHUB_WORKSPACE`?

2021-01-20 11:33 UTC, jeanpsv commented on entrypoint.sh
>  npm install
Não é necessário, o _path_ `GITHUB_WORKSPACE` já é o utilizado quando a execução inicia

2021-01-20 11:35 UTC, jeanpsv commented on README.md
>  ## Inputs
done

2021-01-20 13:57 UTC, inaC approved these changes

2021-01-26 12:19 UTC, merged